// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjpu7m7K1OWNSQRPmFwhSpmCndElGtfGg',
    appId: '1:506267464920:web:273b12f116324f4b1493ad',
    messagingSenderId: '506267464920',
    projectId: 'firstcotton-k1',
    authDomain: 'firstcotton-k1.firebaseapp.com',
    storageBucket: 'firstcotton-k1.appspot.com',
    measurementId: 'G-T0EZL7WGMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyuLPIpmiQ3I7gg3fkuUVI4QWuBmUKwis',
    appId: '1:506267464920:android:8317dc9b36d79d351493ad',
    messagingSenderId: '506267464920',
    projectId: 'firstcotton-k1',
    storageBucket: 'firstcotton-k1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhBFaEFa-QtBJdbKJKTZ7StHb4skPCSrw',
    appId: '1:506267464920:ios:cdc795b6625070f31493ad',
    messagingSenderId: '506267464920',
    projectId: 'firstcotton-k1',
    storageBucket: 'firstcotton-k1.appspot.com',
    iosClientId: '506267464920-k0llp14t7kqo2opa9i56gsgduds3jpnk.apps.googleusercontent.com',
    iosBundleId: 'com.firstcotton.k',
  );
}
